blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Darwin-MFC/darwin-mfc/wiki
    about: Check our documentation and guides
  - name: Discussions
    url: https://github.com/Darwin-MFC/darwin-mfc/discussions
    about: Ask questions and discuss features
  - name: Live Demo
    url: https://mfc.agourakis.med.br
    about: Try the application
